name       : cogl
version    : 1.22.2
release    : 14
source     :
    - http://ftp.gnome.org/pub/gnome/sources/cogl/1.22/cogl-1.22.2.tar.xz : 39a718cdb64ea45225a7e94f88dddec1869ab37a21b339ad058a9d898782c00d
homepage   : http://www.gnome.org
license    :
    - LGPL-2.1
summary    : A modern 3D graphics API
component  : desktop.gnome.core
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(gl)
    - pkgconfig(wayland-egl)
    - pkgconfig(wayland-client)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(pangocairo)
    - pkgconfig(cairo)
    - pkgconfig(xcomposite)
    - pkgconfig(xrandr)
patterns   :
    - demos :
        - /usr/share/cogl/examples-data
        - /usr/bin
description: |
    A modern 3D graphics API
setup      : |
    %configure --disable-static \
               --enable-glib \
               --enable-cogl-pango \
               --disable-cogl-gst \
               --enable-gdk-pixbuf \
               --enable-examples-install \
               --enable-gles2 \
               --enable-gl \
               --enable-cogl-gles2 \
               --enable-glx \
               --enable-wayland-egl-platform \
               --enable-kms-egl-platform \
               --enable-wayland-egl-server \
               --enable-xlib-egl-platform
build      : |
    %make
install    : |
    %make_install
