name       : cogl
version    : 1.22.8
release    : 17
source     :
    - https://download.gnome.org/sources/cogl/1.22/cogl-1.22.8.tar.xz : a805b2b019184710ff53d0496f9f0ce6dcca420c141a0f4f6fcc02131581d759
homepage   : https://blogs.gnome.org/clutter/
license    : LGPL-2.1-or-later
component  :
    - desktop.gnome.core
    - demos : programming.library
summary    : A modern 3D graphics API
description: |
    Cogl is a small open source library for using 3D graphics hardware to draw pretty pictures. The API departs from the flat state machine style of OpenGL and is designed to make it easy to write orthogonal components that can render without stepping on each others toes.
builddeps  :
    - pkgconfig(gbm)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(pangocairo)
    - pkgconfig(wayland-egl)
    - pkgconfig(xcomposite)
    - pkgconfig(xdamage)
    - pkgconfig(xrandr)
patterns   :
    - demos :
        - /usr/share/cogl/examples-data
        - /usr/bin
setup      : |
    %configure --disable-static \
               --disable-cogl-gst \
               --enable-cogl-gles2 \
               --enable-cogl-pango \
               --enable-examples-install \
               --enable-gdk-pixbuf \
               --enable-gl \
               --enable-gles2 \
               --enable-glib \
               --enable-glx \
               --enable-kms-egl-platform \
               --enable-wayland-egl-platform \
               --enable-wayland-egl-server \
               --enable-xlib-egl-platform
build      : |
    %make
install    : |
    %make_install
